In [3]:
import numpy as np

matrixQ = np.array([[1, 2, 3, 2],
                    [4, 7, 6, 4],
                    [8, 9, 3, 5],
                    [1, 4, 2, 2],
                    [1, 0, 2, 3],
                    [1, 3, 3, 4],
                    [1, 1, 5, 3],
                    [1, 0, 3, 4]])

matrixR = np.zeros(shape = (8, 4))

max = np.amax(matrixQ, axis = 0)

for i in range(len(matrixQ)):                   # Из максимального элемента
    for j in range(len(matrixQ[i])):            # каждого столбца
        matrixR[i][j] = max[j] - matrixQ[i][j]  # вычитается элемент строки
                                                #
print("Матрица R\n", matrixR)                   # Матрица R

min = np.amin(matrixQ, axis = 1)                                                # Вальд
valdMaxRow = str(np.argwhere(min == np.amax(min)) + 1)                          # минимум в строках
valdMaxRow = valdMaxRow.replace('[', '').replace(']', '').replace('\n', ',')    # максимум в минимумах
print("Критерий Вальда\n  значение = {}\n  строка = {}"                         # ответ это строка
    .format(np.amax(min), valdMaxRow))                                          # и ее минимальное значение

max = np.amax(matrixQ, axis = 1)                                        # Максимум
MaxRow = str(np.argwhere(max == np.amax(max)) + 1)                      # максимум в строках
MaxRow = MaxRow.replace('[', '').replace(']', '').replace('\n', ',')    # максимум в максимумах
print("Критерий Максимума\n  значение = {}\n  строка = {}"              # ответ это строка
    .format(np.amax(max), MaxRow))                                      # и ее максимальное значение

max = np.amax(matrixR, axis = 1)                                        # Сэвидж
MaxRow = str(np.argwhere(max == np.amin(max)) + 1)                      #
MaxRow = MaxRow.replace('[', '').replace(']', '').replace('\n', ',')    # максимум в строках
print("Критерий Сэвиджа\n  значение = {}\n  строка = {}"                # минимум в максимумах
    .format(np.amin(max), MaxRow))                                      #

a = 0.6                                                                 # Гурвиц
Ci = [0] * len(matrixQ)                                                 #
for i in range(len(matrixQ)):                                           # вычисляется
    Ci[i] = round(a * np.min(matrixQ[i])                                # a * np.min(matrixR[i] + (1 - a) * np.max(matrixR[i])
    + (1 - a) * np.max(matrixQ[i]), 2)                                  # для каждой строки
MaxRow = str(np.argwhere(Ci == np.amax(Ci)) + 1)                        # берется их максимум
MaxRow = MaxRow.replace('[', '').replace(']', '').replace('\n', ',')    #
print("Критерий Гурвица\n", Ci)                                         #
print("  значение = {}\n  строка = {}".format(np.amax(Ci), MaxRow))     #

Di = [0] * len(matrixQ)                                                 # Лаплас
for i in range(len(matrixQ)):                                           #
        Di[i] = sum(matrixQ[i]) / 4                                     # суммируется каждая строка делится на колво элементов в строке
MaxRow = str(np.argwhere(Di == np.amax(Di)) + 1)                        # берется максимальное
MaxRow = MaxRow.replace('[', '').replace(']', '').replace('\n', ',')    # число из сумм
print("Критерий Лапласа\n", Di)                                         #
print("  значение = {}\n  строка = {}".format(np.amax(Di), MaxRow))     #

Di = [0] * len(matrixQ)                                                 # Байес
for i in range(len(matrixQ)):                                           #
        Di[i] = sum(matrixQ[i]) * 0.25                                  # суммируется каждая строка делится на колво элементов в строке
MaxRow = str(np.argwhere(Di == np.amax(Di)) + 1)                        # берется максимальное
MaxRow = MaxRow.replace('[', '').replace(']', '').replace('\n', ',')    # число из сумм
print("Критерий Байеса\n", Di)                                          #
print("  значение = {}\n  строка = {}".format(np.amax(Di), MaxRow))     #

Матрица R
 [[7. 7. 3. 3.]
 [4. 2. 0. 1.]
 [0. 0. 3. 0.]
 [7. 5. 4. 3.]
 [7. 9. 4. 2.]
 [7. 6. 3. 1.]
 [7. 8. 1. 2.]
 [7. 9. 3. 1.]]
Критерий Вальда
  значение = 4
  строка = 2
Критерий Максимума
  значение = 9
  строка = 3
Критерий Сэвиджа
  значение = 3.0
  строка = 3
Критерий Гурвица
 [1.8, 5.2, 5.4, 2.2, 1.2, 2.2, 2.6, 1.6]
  значение = 5.4
  строка = 3
Критерий Лапласа
 [2.0, 5.25, 6.25, 2.25, 1.5, 2.75, 2.5, 2.0]
  значение = 6.25
  строка = 3
Критерий Байеса
 [2.0, 5.25, 6.25, 2.25, 1.5, 2.75, 2.5, 2.0]
  значение = 6.25
  строка = 3
